# configuration for gcp cloud repo buil
steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - beta
  - functions
  - deploy
  - function-1
  - --region=us-central1
  - --trigger-http
  - --source=build/
  - --entry-point=helloWorld # Function name

- name: gcr.io/cloud-builders/gcloud
  args:
    - beta
    - functions
    - deploy
    - function-2
    - --region=us-central1
    - --trigger-http
    - --source=build/
    - --entry-point=helloWorld # Function name
