# configuration for gcp cloud repo build
steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - functions
      - deploy
      - processRequest
      - --region=europe-west1 #europe-west1, europe-west2, us-central1, us-east1, asia-northeast1, asia-east2
      - --runtime=nodejs8 #nodejs6 #nodejs8 #nodejs10 #(beta) #python37 #(Python 3.7) #go111 #Go 1.11
      - --trigger-http
      - --source=web/
      - --entry-point=procRequest # Function name

  - name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - functions
      - deploy
      - processBody
      - --region=europe-west1 #europe-west1, europe-west2, us-central1, us-east1, asia-northeast1, asia-east2
      - --runtime=nodejs8 #nodejs6 #nodejs8 #nodejs10 #(beta) #python37 #(Python 3.7) #go111 #Go 1.11
      - --trigger-http
      - --source=web/
      - --entry-point=procBody #Function name
